sudo: required
services:
  - docker
before_install:
  - docker build -t annie/docker-react -f Dockerfile.dev .
script:
  - echo $TRAVIS_COMMIT
  - docker run annie/docker-react npm run test -- --verbose=true
  
